name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports: ["6379:6379"]
        options: --entrypoint redis-server

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install atlas-cli
      run: curl -sSf https://atlasgo.sh | sh

    - name: Run migrations
      run: |
        make atlas-inspect
        make atlas-apply
        make migrate
    
    - name: Run tests
      run: make test
          